name: Percy Visual Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  percy:
    runs-on: windows-latest
    
    steps:
      # Checkout the current repository
      - name: Checkout current repository
        uses: actions/checkout@v2

      # Checkout the other public repository (Percy project)
      - name: Checkout other public repository (Percy project)
        uses: actions/checkout@v2
        with:
          repository: 'Adhit2013/PercyHandsOn'
          path: percy_project

      # Set up Java 17 (includes Maven setup)
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      # Install dependencies for the current repo
      - name: Install dependencies for current repo
        run: npm install -g @percy/cli

      # Check Maven version (to confirm it's installed)
      - name: Check Maven version
        run: mvn -version

      # Run Percy visual tests
      - name: Run Percy visual tests
        shell: bash # Use bash for multi-line commands
        run: |
          cd percy_project
          npx percy exec -- mvn test
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
